import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import SocialBar from '../components/socialBar'
import Testimonial from '../components/Testimonials/Testimonial'



export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title className=''>Ecommerce Port</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<SocialBar/>
<Navbar/>
<Banner/>
<Testimonial/>
<Footer/>
    
    </div>
  )
}
